backend:
  name: github
  repo: Sushmitha5699/portfolio
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "main"
    label: "Main Page"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Paragraph", name: "paragraph", widget: "text" }
