backend:
  name: github
  repo: Sushmitha5699/portfolio
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: homepage
    label: "Homepage Content"
    files:
      - file: "index.html"
        label: "Main Page"
        name: "main"
        fields:
          - label: "Title"
            name: title
            widget: string
          - label: "Intro Text"
            name: intro
            widget: text
