backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

media_folder: "assets/uploads"  # We use the 'assets' folder for media uploads
public_folder: "/assets/uploads"  # The public path for images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Blog Creator Name", name: "bloggerName", widget: "string", required: true }