backend:
  name: github
  repo: Sushmitha5699/portfolio
  branch: main  # or the branch you are using

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "intro", widget: "text" }
