backend:
  name: git-gateway
  branch: main # or 'master' if your repo uses that

media_folder: "assets/uploads" # where uploaded images will go inside your repo
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
