backend:
  name: github
  repo: Sushmitha5699/portfolio
  branch: main

media_folder: "assets/uploads" # where uploaded images go
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
